//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoteView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_admin {
            get {
                object obj = ResourceManager.GetObject("bg_admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_noteview {
            get {
                object obj = ResourceManager.GetObject("bg_noteview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_in {
            get {
                object obj = ResourceManager.GetObject("check_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_out {
            get {
                object obj = ResourceManager.GetObject("check_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE IF NOT EXISTS Client (
        ///	id INT NOT NULL AUTO_INCREMENT,
        ///	
        ///	nameTitle TEXT,
        ///	firstName TEXT NOT NULL,
        ///	middleName TEXT,
        ///	lastName TEXT NOT NULL,
        ///	
        ///	streetAd TEXT,
        ///	zipCode TEXT NOT NULL,
        ///	cityAd TEXT,
        ///	countryAd TEXT,
        ///	stateProvinceAd TEXT,
        ///	nationality TEXT,
        ///
        ///	guestNote TEXT,
        ///	
        ///	telephone TEXT,
        ///	mobile TEXT NOT NULL,
        ///	email TEXT,
        ///	
        ///	amount INT,
        ///		
        ///	vehicleBrand TEXT,
        ///	vehicleModel TEXT,
        ///	vehicleColor TEXT,
        ///	license TEXT,
        ///	
        ///	PRIMARY KEY (id)
        ///);
        ///.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_arrow {
            get {
                object obj = ResourceManager.GetObject("left_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_booking {
            get {
                object obj = ResourceManager.GetObject("new_booking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_booking1 {
            get {
                object obj = ResourceManager.GetObject("new_booking1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noteview_icon {
            get {
                object obj = ResourceManager.GetObject("noteview_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noteview_superlabel {
            get {
                object obj = ResourceManager.GetObject("noteview_superlabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap post_charges {
            get {
                object obj = ResourceManager.GetObject("post_charges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE IF NOT EXISTS Reservation (
        ///	id INT NOT NULL AUTO_INCREMENT,
        ///	clientId INT NOT NULL,
        ///	roomId INT NOT NULL,
        ///	arrival DATE NOT NULL,
        ///	-- From spec, &quot;nights&quot; can be calculated in the client not in the database
        ///	departure DATE NOT NULL,
        ///	adultCount INT NOT NULL,
        ///	childCount INT NOT NULL,
        ///	issuer INT NOT NULL,
        ///	issuedDate DATE NOT NULL,
        ///	state TEXT NOT NULL, -- Can be &apos;WAITING&apos;, &apos;IN_HOUSE&apos;, &apos;CHECKED_OUT&apos;
        ///	
        ///	PRIMARY KEY (id),
        ///	FOREIGN KEY (clientId) REFERENCES Client(id),
        ///	FOREIGN KE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reservation {
            get {
                return ResourceManager.GetString("reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow {
            get {
                object obj = ResourceManager.GetObject("right_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Room (
        ///	id INT NOT NULL AUTO_INCREMENT,
        ///	-- TODO: implement supplemental data
        ///	roomNumber TEXT NOT NULL,
        ///	roomType TEXT NOT NULL,
        ///	rate INT NOT NULL,
        ///	capacity INT NOT NULL,
        ///	
        ///	PRIMARY KEY (id)
        ///);
        ///.
        /// </summary>
        internal static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search1 {
            get {
                object obj = ResourceManager.GetObject("search1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Service (
        ///  id INT NOT NULL AUTO_INCREMENT,
        ///  
        ///	serviceGroup TEXT NOT NULL,
        ///	serviceName TEXT NOT NULL,
        ///	rate DOUBLE NOT NULL,
        ///	quantity INT NOT NULL,
        ///	
        ///	PRIMARY KEY (id)
        ///);.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE IF NOT EXISTS UserInfo (
        ///	id INT NOT NULL AUTO_INCREMENT,
        ///	firstName TEXT NOT NULL,
        ///	lastName TEXT NOT NULL,
        ///	userType TEXT NOT NULL,
        ///	userName TEXT NOT NULL,
        ///	password TEXT NOT NULL,
        ///	
        ///	PRIMARY KEY (id)
        ///);
        ///.
        /// </summary>
        internal static string user_info {
            get {
                return ResourceManager.GetString("user_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap willkommen {
            get {
                object obj = ResourceManager.GetObject("willkommen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
