CREATE TABLE IF NOT EXISTS Voucher {
	id INT NOT NULL AUTO_INCREMENT,
	Discount INT NOT NULL,
	VoucherType TEXT NOT NULL,
	Code TEXT NOT NULL,
	
	PRIMARY KEY (id)
}

CREATE TABLE IF NOT EXISTS Services {
    id INT NOT NULL AUTO_INCREMENT,
	VoucherID INT,
	
	ServicesType TEXT NOT NULL,
	ServiceName TEXT NOT NULL,
	Price DOUBLE NOT NULL,
	QTY INT NOT NULL,
	
	PRIMARY KEY (id),
	FOREIGN KEY (VoucherID) REFERENCES Voucher(id)
	}
		

CREATE TABLE IF NOT EXISTS ResServices {
	id INT NOT NULL AUTO_INCREMENT,
	
	ServiceID INT NOT NULL,
	WalkInID INT NOT NULL,
	ResDate DATE NOT NULL,
	
	PRIMARY KEY (id),
	FOREIGN KEY (ServiceID) REFERENCES Services(id),
	FOREIGN KEY (WalkInID) REFERENCES Reservation(id)
}
